/* ============================================================
   Yenileme & İptal Panosu — sıfır dış bağımlılık.
   Akış: 1) Tara (Pass 1 + Pass 2, TÜM populasyon için, tek seferde) ->
   2) Filtre seç (bellek içi, dosya okuması yok, anında günceller).
   ============================================================ */

const PALETTE = {
  renew: '#20463a',
  renewLight: '#5c7d70',
  cancel: '#762c1f',
  cancelLight: '#a8604c',
  grid: '#b3a37c',
  text: '#4a4235',
  textDim: '#6b6252',
};

const UNKNOWN_LABEL = '(bilinmiyor)';

const els = {
  fileInput: document.getElementById('fileInput'),
  fileLabel: document.getElementById('fileLabel'),
  scanBtn: document.getElementById('scanBtn'),
  resetBtn: document.getElementById('resetBtn'),
  applyFilterBtn: document.getElementById('applyFilterBtn'),
  progressWrap: document.getElementById('progressWrap'),
  cookingWrap: document.getElementById('cookingWrap'),
  progressFill: document.getElementById('progressFill'),
  progressLabel: document.getElementById('progressLabel'),
  log: document.getElementById('log'),
  emptyState: document.getElementById('emptyState'),
  filterSection: document.getElementById('filterSection'),
  filterGrid: document.getElementById('filterGrid'),
  statsSection: document.getElementById('statsSection'),
  statRow: document.getElementById('statRow'),
  visual1: document.getElementById('visual1'),
  visual1Grid: document.getElementById('visual1Grid'),
  visual3: document.getElementById('visual3'),
  visual3Holder: document.getElementById('visual3Holder'),
  visual4: document.getElementById('visual4'),
  visual4Grid: document.getElementById('visual4Grid'),
  scatterGrid: document.getElementById('scatterGrid'),
  day2CancelGrid: document.getElementById('day2CancelGrid'),
  adv1Grid: document.getElementById('adv1Grid'),
  adv2Grid: document.getElementById('adv2Grid'),
  cs1Grid: document.getElementById('cs1Grid'),
  cs2Grid: document.getElementById('cs2Grid'),
  cs3Grid: document.getElementById('cs3Grid'),
  cs5Grid: document.getElementById('cs5Grid'),
  cs6Grid: document.getElementById('cs6Grid'),
  cs7Grid: document.getElementById('cs7Grid'),
  cs7RevGrid: document.getElementById('cs7RevGrid'),
  csX: document.getElementById('csX'),
  csExclude: document.getElementById('csExclude'),
  csSignal: document.getElementById('csSignal'),
  csF1: document.getElementById('csF1'),
  csF2: document.getElementById('csF2'),
  csF3: document.getElementById('csF3'),
  csF4: document.getElementById('csF4'),
  cs8Grid: document.getElementById('cs8Grid'),
  csC1: document.getElementById('csC1'),
  csC2: document.getElementById('csC2'),
  csC3: document.getElementById('csC3'),
  csComboN: document.getElementById('csComboN'),
  cs9Grid: document.getElementById('cs9Grid'),
  cs10Grid: document.getElementById('cs10Grid'),
  csDistEventBin: document.getElementById('csDistEventBin'),
  csDistEventCap: document.getElementById('csDistEventCap'),
  csDistMinuteBin: document.getElementById('csDistMinuteBin'),
  csDistMinuteCap: document.getElementById('csDistMinuteCap'),
  nsImpliedGrid: document.getElementById('nsImpliedGrid'),
  ns0Grid: document.getElementById('ns0Grid'),
  ns1Grid: document.getElementById('ns1Grid'),
  ns2Grid: document.getElementById('ns2Grid'),
  ns3Grid: document.getElementById('ns3Grid'),
  ns4Grid: document.getElementById('ns4Grid'),
  ns5Grid: document.getElementById('ns5Grid'),
  nsDayTopN: document.getElementById('nsDayTopN'),
  nsDayIgnoreBox: document.getElementById('nsDayIgnoreBox'),
  nsIgnoreBox: document.getElementById('nsIgnoreBox'),
  nsReclassifyBox: document.getElementById('nsReclassifyBox'),
  gf6Grid: document.getElementById('gf6Grid'),
  gf7Grid: document.getElementById('gf7Grid'),
  aiSegment: document.getElementById('aiSegment'),
  aiSegNote: document.getElementById('aiSegNote'),
  cs11Grid: document.getElementById('cs11Grid'),
  cs12Grid: document.getElementById('cs12Grid'),
  csPrecN: document.getElementById('csPrecN'),
  csPrecIgnoreBox: document.getElementById('csPrecIgnoreBox'),
  nsMinSpan: document.getElementById('nsMinSpan'),
  nsTopN: document.getElementById('nsTopN'),
  csRiskEvent: document.getElementById('csRiskEvent'),
  csRiskEvents: document.getElementById('csRiskEvents'),
  csRiskMinutes: document.getElementById('csRiskMinutes'),
  gf1Grid: document.getElementById('gf1Grid'),
  gf2Grid: document.getElementById('gf2Grid'),
  gf3Grid: document.getElementById('gf3Grid'),
  gf4Grid: document.getElementById('gf4Grid'),
  gf5Grid: document.getElementById('gf5Grid'),
  imgRenewalGrid: document.getElementById('imgRenewalGrid'),
};

// tarama sonrasi tum sonuclari burada tutuyoruz, boylece filtreyi
// degistirip tekrar tekrar "Filtreli Analizi Calistir"a basabiliyorsun,
// dosyayi/Pass1'i her seferinde yeniden calistirmadan.
let state = null;
let selectedFile = null;

